apiVersion: v2
name: opendj
version: 0.2.0
description: Chart for OpenDJ, used by Sam(Terra IAM service) as well as various Terra applications' OIDC proxy deploys
type: application
keywords:
  - dsp
  - broadinstitute
  - terra
  - opendj
sources:
  - https://github.com/broadinstitute/firecloud-opendj
  - https://github.com/broadinstitute/terra-helm/tree/master/charts/opendj
