apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-prometheus-configmap
  labels:
{{ include "externalcreds.labels" . | indent 4 }}
data:
{{- if .Values.prometheus.enabled }}
  prometheusJmx.yaml: |
{{ include "externalcreds.config.prometheusJmx" . | indent 4 }}
{{- end }}
