{{- define "libchart.ingress.tpl" -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: "{{ .Chart.Name }}-ingress-frontendconfig"
    kubernetes.io/ingress.global-static-ip-name: {{ required "ingress.staticIpName value is required" .Values.ingress.staticIpName | quote }}
{{- if not (empty .Values.ingress.cert.preSharedCerts) }}
    ingress.gcp.kubernetes.io/pre-shared-cert: {{ .Values.ingress.cert.preSharedCerts | join "," | quote }}
{{- end }}
    kubernetes.io/ingress.allow-http: "false"
  {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backend:
    serviceName: {{ .Chart.Name }}-service
    servicePort: 443
{{- end -}}

{{- define "libchart.ingress" -}}
{{- include "libchart.util.merge" (append . "libchart.ingress.tpl") -}}
{{- end -}}
