apiVersion: v2
name: firecloudui
version: 0.3.0
description: Chart for Firecloud UI service in Terra
type: application
keywords:
  - dsp
  - broadinstitute
  - terra
  - firecloudui
sources:
  - https://github.com/broadinstitute/terra-helm/tree/master/charts
  - https://github.com/broadinstitute/firecloud-ui
dependencies:
- name: ingress-library
  condition: ingress.enabled
  version: 0.1.0
  repository: file://../ingresslibchart
