apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.name }}-psp-role
  labels:
    {{- include "revere.labels" . | nindent 4 }}
rules:
- apiGroups: ["extensions"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - {{ .Release.name }}-psp
