{{- define "ingresslibchart.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    # Associate a backend config with the ingress: https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#associating_backendconfig_with_your_ingress
    cloud.google.com/backend-config: '{"default": "{{ .Values.name }}-ingress-backendconfig"}'
    # Enable container-native load balancing https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing
    cloud.google.com/neg: '{"ingress": true}'
    # Enable TLS between LB and apache proxy https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb
    cloud.google.com/app-protocols: '{"https":"HTTPS"}'
spec:
  type: ClusterIP
  selector:
    {{- include "helm.labels" . | nindent 4 }}
 {{- with .Values.ingress.ports }}
  ports:
  {{- range .Values.ingress.ports }}
  - name: {{ .name | quote }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
