apiVersion: v2
name: cromiam
version: 0.10.0
appVersion: latest
description: Chart for cromiam service in Terra [WIP]
type: application
keywords:
  - dsp
  - broadinstitute
  - terra
  - cromiam
sources:
  - https://github.com/broadinstitute/terra-helm/tree/master/charts
  - https://github.com/broadinstitute/cromiam
dependencies:
- name: ingress-library
  condition: ingress.enabled
  version: 0.1.0
  repository: file://../ingresslibchart
