apiVersion: v2
name: postgres

version: 0.1.0

description: Library chart for an ephemeral PostgreSQL database container
type: library

keywords:
- dsp
- broadinstitute
- database
- postgres

sources:
- https://github.com/broadinstitute/terra-helm/tree/master/charts
