apiVersion: v2
name: thurloe
version: 0.3.0
description: Chart for Thurloe service in Terra
type: application
keywords:
  - dsp
  - broadinstitute
  - terra
  - thurloe
sources:
  - https://github.com/broadinstitute/terra-helm/tree/master/charts
  - https://github.com/broadinstitute/thurloe
