apiVersion: v2
name: dsp-argocd
version: 0.19.0
description: Helm Chart with extra resources for the DSP ArgoCD instance
type: application
maintainers:
  - name: DSP DevOps
    email: dsp-devops@broadinstitute.org
sources:
  - https://github.com/broadinstitute/terra-helm/tree/master/charts/dsp-argocd
dependencies:
  - name: argo-cd
    version: 2.9.2
    repository: https://argoproj.github.io/argo-helm
  - name: dsp-argocd-notifications
    alias: notifications
    version: 0.0.1
    repository: file://local-charts/dsp-argocd-notifications
