apiVersion: v2
name: rawls
version: 0.12.0
appVersion: latest
description: Chart for Rawls service in Terra
type: application
keywords:
  - dsp
  - broadinstitute
  - terra
  - rawls
sources:
  - https://github.com/broadinstitute/terra-helm/tree/master/charts
  - https://github.com/broadinstitute/rawls
dependencies:
  - name: liquibase-migration
    condition: migration.enabled
    version: 0.2.0
    repository: https://broadinstitute.github.io/terra-helm/
